services:
  grafana:
    # image: grafana/grafana-enterprise:10.1.5
    image: grafana/grafana-oss:10.1.5
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
    #  - GF_INSTALL_PLUGINS=grafana-clock-panel
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    healthcheck:
      test: ['CMD', 'wget', 'http://localhost:3000/healthz']
      interval: 10s
      timeout: 15s
      retries: 3
      start_period: 0s
    depends_on:
      prometheus:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=2d'
      - '--storage.tsdb.wal-compression'
    healthcheck:
      test: ['CMD', 'wget', 'http://localhost:9090']
      interval: 10s
      timeout: 15s
      retries: 3
      start_period: 0s

volumes:
  grafana-storage:
  prometheus-data:
